# Generated by Django 5.0.7 on 2024-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
