# Generated by Django 5.0.7 on 2024-08-01 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0002_membre_email_membre_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('librairie', models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, to='arch_portal.librairie')),
                ('livre', models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, to='arch_portal.livre')),
                ('proprietaire', models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, to='arch_portal.membre')),
            ],
            options={
                'verbose_name': 'Commande de Livre',
                'verbose_name_plural': 'Les commandes ',
            },
        ),
    ]
