# Generated by Django 5.0.7 on 2024-08-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0004_famille_famille_mere'),
        ('arch_portal', 'static_data'),
    ]

    operations = [
    ]
