# Generated by Django 5.0.7 on 2024-09-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0006_association_adhesion_association_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='communaute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arch_portal.communaute'),
        ),
    ]
