# Generated by Django 5.0.7 on 2024-09-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0007_association_communaute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='pwd',
            field=models.CharField(max_length=300),
        ),
    ]
