# Generated by Django 5.0.7 on 2024-09-04 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0008_alter_membre_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('VIEW_ACCOUNT', 'VIEW_ACCOUNT'), ('EDIT_ACCOUNT', 'EDIT_ACCOUNT'), ('DELETE_ACCOUNT', 'DELETE_ACCOUNT'), ('VIEW_SHOP_USERS', 'VIEW_SHOP_USERS'), ('EDIT_SHOP_USERS', 'EDIT_SHOP_USERS'), ('DELETE_SHOP_USERS', 'DELETE_SHOP_USERS'), ('VIEW_USERS', 'VIEW_USERS'), ('EDIT_USERS', 'EDIT_USERS'), ('DELETE_USERS', 'DELETE_USERS'), ('VIEW_SHOP', 'VIEW_SHOP'), ('EDIT_SHOP', 'EDIT_SHOP'), ('DELETE_SHOP', 'DELETE_SHOP'), ('VIEW_PRODUCTS', 'VIEW_PRODUCTS'), ('EDIT_PRODUCTS', 'EDIT_PRODUCTS'), ('DELETE_PRODUCTS', 'DELETE_PRODUCTS'), ('VIEW_ALL_ORDERS', 'VIEW_ALL_ORDERS'), ('VIEW_OWN_ORDERS', 'VIEW_OWN_ORDERS'), ('EDIT_OWN_ORDERS', 'EDIT_OWN_ORDERS'), ('DELETE_OWN_ORDERS', 'DELETE_OWN_ORDERS'), ('VIEW_CART_PRODUCTS', 'VIEW_CART_PRODUCTS'), ('EDIT_CART_PRODUCTS', 'EDIT_CART_PRODUCTS'), ('DELETE_CART_PRODUCTS', 'DELETE_CART_PRODUCTS'), ('VIEW_SHOP_REVIEWS', 'VIEW_SHOP_REVIEWS'), ('MANAGE_SHOP_REVIEWS', 'MANAGE_SHOP_REVIEWS'), ('VIEW_REVIEWS', 'VIEW_REVIEWS'), ('EDIT_REVIEWS', 'EDIT_REVIEWS'), ('DELETE_REVIEWS', 'DELETE_REVIEWS'), ('VIEW_CUSTOMER_REVIEWS', 'VIEW_CUSTOMER_REVIEWS'), ('MANAGE_CUSTOMERS_REVIEWS', 'MANAGE_CUSTOMERS_REVIEWS'), ('GENERATE_COLLECTION_LISTS', 'GENERATE_COLLECTION_LISTS'), ('VIEW_COLLECTION_LISTS', 'VIEW_COLLECTION_LISTS'), ('EDIT_COLLECTION_LISTS', 'EDIT_COLLECTION_LISTS'), ('DELETE_COLLECTION_LISTS', 'DELETE_COLLECTION_LISTS'), ('VIEW_WAREHOUSE_USERS', 'VIEW_WAREHOUSE_USERS'), ('EDIT_WAREHOUSE_USERS', 'EDIT_WAREHOUSE_USERS'), ('DELETE_WAREHOUSE_USERS', 'DELETE_WAREHOUSE_USERS'), ('VIEW_WAREHOUSE_STATISTICS', 'VIEW_WAREHOUSE_STATISTICS'), ('VIEW_SHOP_MARKETPLACE_REPORTS', 'VIEW_SHOP_AND_MARKETPLACE_REPORTS'), ('GENERATE_DELIVERY_LISTS', 'GENERATE_DELIVERY_LISTS'), ('VIEW_DELIVERY_LISTS', 'VIEW_DELIVERY_LISTS'), ('EDIT_DELIVERY_LISTS', 'EDIT_DELIVERY_LISTS'), ('DELETE_DELIVERY_LISTS', 'DELETE_DELIVERY_LISTS'), ('VIEW_ALL_USERS', 'VIEW_ALL_USERS'), ('EDIT_ALL_USERS', 'EDIT_ALL_USERS')], max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='commandelivre',
            options={'verbose_name': 'Commande de Livre', 'verbose_name_plural': 'Les commandes de livres'},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('COMM_CHEF', 'COMM_CHEF'), ('COMM_USER', 'COMM_USER'), ('COMM_ADMIN', 'COMM_ADMIN'), ('LIB_MANAGER', 'LIB_MANAGER'), ('LIB_USER', 'LIB_USER')], max_length=50, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('permissions', models.ManyToManyField(to='arch_portal.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='role',
            field=models.ManyToManyField(to='arch_portal.role'),
        ),
    ]
