# Generated by Django 5.0.7 on 2024-09-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0009_permission_alter_commandelivre_options_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='nommere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mama', to='arch_portal.membre'),
        ),
        migrations.AddField(
            model_name='membre',
            name='nompere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papa', to='arch_portal.membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mere',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='pere',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='nom',
            field=models.CharField(choices=[('VOIR_FAMILLE', 'VOIR_FAM'), ('VOIR_COMMUNAUTE', 'VOIR_COM'), ('VOIR_MARCHE', 'VOIR_MAR'), ('ADD_FAMILLE', 'ADD_FAM'), ('ADD_COMMUNAUTE', 'ADD_COM'), ('ADD_MARCHE', 'ADD_MAR'), ('ADD_ASSOCIATION', 'ADD_ASSO'), ('ADD_EVENEMENT', 'ADD_EVEN'), ('ADD_LIBRAIRIE', 'ADD_LIB'), ('ADD_LIVRE', 'ADD_LIV'), ('COMMANDER_LIVRE', 'COM_LIV'), ('ADD_MEMBRE', 'ADD_MEM')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('MEMBRE', 'MEMBRE'), ('SUPERADMIN', 'SUPERADMIN'), ('ADMIN', 'ADMIN'), ('LIBRAIRE', 'LIBRAIRE')], max_length=50, unique=True),
        ),
    ]
