# Generated by Django 5.0.7 on 2024-12-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "arch_portal",
            "0010_membre_nommere_membre_nompere_alter_membre_mere_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="livre",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Physique", "Livre papier"),
                    ("Numerique", "Livre numerique"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="mere",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="membre",
            name="nommere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mama",
                to="arch_portal.membre",
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="nompere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="papa",
                to="arch_portal.membre",
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="pere",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
