# Generated by Django 5.0.7 on 2024-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "arch_portal",
            "0011_livre_type_alter_membre_mere_alter_membre_nommere_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="communaute",
            name="listerois",
            field=models.CharField(default="", max_length=150),
        ),
    ]
