# Generated by Django 5.0.7 on 2025-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0012_communaute_listerois"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="fichier",
            field=models.ImageField(default="", upload_to="book_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livre",
            name="cover_image",
            field=models.ImageField(default="", upload_to="couvertures/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livre",
            name="file",
            field=models.FileField(default="", upload_to="livres/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livre",
            name="images",
            field=models.ManyToManyField(blank=True, null=True, to="arch_portal.image"),
        ),
        migrations.AddField(
            model_name="livre",
            name="isbn",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livre",
            name="langue",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
