# Generated by Django 5.0.7 on 2025-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0013_image_fichier_livre_cover_image_livre_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livre",
            name="cover_image",
        ),
        migrations.AlterField(
            model_name="livre",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="livres/"),
        ),
        migrations.AlterField(
            model_name="livre",
            name="isbn",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="livre",
            name="langue",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
