# Generated by Django 5.0.7 on 2025-02-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0014_remove_livre_cover_image_alter_livre_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="sonlivre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sonlivre",
                to="arch_portal.livre",
            ),
        ),
    ]
