# Generated by Django 5.0.7 on 2025-02-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0015_image_sonlivre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=50)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("appli", models.CharField(blank=True, max_length=10)),
                ("avantages", models.TextField(blank=True)),
                (
                    "prix",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "prix",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("debut", models.DateTimeField(auto_now_add=True)),
                ("fin", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("duree", models.IntegerField(default=365)),
                (
                    "membre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="arch_portal.membre",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.plan",
                    ),
                ),
            ],
        ),
    ]
