# Generated by Django 5.0.7 on 2025-02-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0016_plan_abonnement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="prix",
            field=models.IntegerField(blank=True),
        ),
    ]
