# Generated by Django 5.0.7 on 2025-02-04 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0017_alter_abonnement_is_active_alter_abonnement_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="membre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="arch_portal.membre",
            ),
        ),
    ]
