# Generated by Django 5.0.7 on 2025-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0018_alter_abonnement_membre"),
    ]

    operations = [
        migrations.AddField(
            model_name="livre",
            name="stock",
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
