# Generated by Django 5.0.7 on 2025-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0019_livre_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="stock",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
