# Generated by Django 5.0.7 on 2025-02-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0020_alter_livre_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="membre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abonnements",
                to="arch_portal.membre",
            ),
        ),
    ]
