# Generated by Django 5.0.7 on 2025-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0021_alter_abonnement_membre"),
    ]

    operations = [
        migrations.AddField(
            model_name="communaute",
            name="administrateurs",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="com_admins",
                to="arch_portal.membre",
            ),
        ),
    ]
