# Generated by Django 5.0.7 on 2025-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0022_communaute_administrateurs"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="communautes",
            field=models.ManyToManyField(
                blank=True, null=True, to="arch_portal.communaute"
            ),
        ),
    ]
