# Generated by Django 5.0.7 on 2025-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0025_famille_administrateurs_alter_permission_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="familles",
            field=models.ManyToManyField(
                null=True, related_name="membres_famille", to="arch_portal.famille"
            ),
        ),
    ]
