# Generated by Django 5.0.7 on 2025-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0026_alter_membre_familles"),
    ]

    operations = [
        migrations.AddField(
            model_name="communaute",
            name="publique",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="famille",
            name="publique",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("MEMBRE", "MEMBRE"),
                    ("SUPERADMIN", "SUPERADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("LIBRAIRE", "LIBRAIRE"),
                    ("CLIENT", "CLIENT"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
