# Generated by Django 5.0.7 on 2025-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0027_communaute_publique_famille_publique_alter_role_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="communautes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="membres_communaute",
                to="arch_portal.communaute",
            ),
        ),
    ]
