# Generated by Django 5.0.7 on 2025-02-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0028_alter_membre_communautes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalleAttenteCommunaute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_demande", models.DateField(auto_now_add=True)),
                ("date_validation", models.DateField()),
                ("valide", models.BooleanField(default=False)),
                (
                    "communaute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.communaute",
                    ),
                ),
                (
                    "personne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.membre",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validateur",
                        to="arch_portal.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": " Salle attente communaute",
            },
        ),
        migrations.CreateModel(
            name="SalleAttenteFamille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_demande", models.DateField(auto_now_add=True)),
                ("date_validation", models.DateField()),
                ("valide", models.BooleanField(default=False)),
                (
                    "famille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.famille",
                    ),
                ),
                (
                    "personne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.membre",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validateur_fam",
                        to="arch_portal.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": " Salle attente familles",
            },
        ),
    ]
