# Generated by Django 5.0.7 on 2025-02-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0029_salleattentecommunaute_salleattentefamille"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salleattentecommunaute",
            name="date_validation",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="salleattentefamille",
            name="date_validation",
            field=models.DateField(null=True),
        ),
    ]
