# Generated by Django 5.0.7 on 2025-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0030_alter_salleattentecommunaute_date_validation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salleattentecommunaute",
            name="date_demande",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="salleattentefamille",
            name="date_demande",
            field=models.DateField(auto_now=True),
        ),
    ]
