# Generated by Django 5.0.7 on 2025-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0031_alter_salleattentecommunaute_date_demande_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=100)),
                ("contenu", models.CharField(max_length=250)),
                ("date_ajout", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": " Message",
                "verbose_name_plural": "Les Messages",
            },
        ),
        migrations.AddField(
            model_name="membre",
            name="messages",
            field=models.ManyToManyField(
                null=True, related_name="membres_message", to="arch_portal.message"
            ),
        ),
    ]
