# Generated by Django 5.0.7 on 2025-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0032_message_membre_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="publique",
            field=models.BooleanField(default=True),
        ),
    ]
