# Generated by Django 5.0.7 on 2025-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0033_association_publique"),
    ]

    operations = [
        migrations.AddField(
            model_name="famille",
            name="associations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="association_familles",
                to="arch_portal.association",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="nom",
            field=models.CharField(
                choices=[
                    ("VOIR_FAMILLE", "VOIR_FAM"),
                    ("VOIR_COMMUNAUTE", "VOIR_COM"),
                    ("VOIR_MARCHE", "VOIR_MAR"),
                    ("ADD_FAMILLE", "ADD_FAM"),
                    ("ADD_COMMUNAUTE", "ADD_COM"),
                    ("ADD_COMMUNAUTE_ADMIN", "ADD_COM_ADMIN"),
                    ("ADD_FAMILLE_ADMIN", "ADD_FAM_ADMIN"),
                    ("ADD_MARCHE", "ADD_MAR"),
                    ("ADD_ASSOCIATION", "ADD_ASSO"),
                    ("VOIR_ASSOCIATION", "VOIR_ASSO"),
                    ("VOIR_MEMBRE_ASSOCIATION", "VOIR_MEM_ASSO"),
                    ("ADD_EVENEMENT", "ADD_EVEN"),
                    ("ADD_LIBRAIRIE", "ADD_LIB"),
                    ("ADD_LIVRE", "ADD_LIV"),
                    ("COMMANDER_LIVRE", "COM_LIV"),
                    ("ADD_MEMBRE", "ADD_MEM"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
