# Generated by Django 5.0.7 on 2025-02-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0034_famille_associations_alter_permission_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="famille",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="arch_portal.famille",
            ),
        ),
    ]
