# Generated by Django 5.0.7 on 2025-02-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0035_association_famille"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalleAttenteAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_demande", models.DateField(auto_now=True)),
                ("date_validation", models.DateField(null=True)),
                ("valide", models.BooleanField(default=False)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.association",
                    ),
                ),
                (
                    "personne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch_portal.membre",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validateur_asso",
                        to="arch_portal.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": " Salle attente association",
            },
        ),
    ]
