# Generated by Django 5.0.7 on 2025-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0036_salleattenteassociation"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="administrateurs",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="asso_admins",
                to="arch_portal.membre",
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="associations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="membres_association",
                to="arch_portal.association",
            ),
        ),
    ]
