# Generated by Django 5.0.7 on 2025-02-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_portal", "0037_association_administrateurs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="communaute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="arch_portal.communaute",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="famille",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="arch_portal.famille",
            ),
        ),
    ]
