# Generated by Django 5.2.6 on 2026-01-23 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0038_alter_association_communaute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='nom',
            field=models.CharField(choices=[('VOIR_FAMILLE', 'VOIR_FAM'), ('VOIR_COMMUNAUTE', 'VOIR_COM'), ('VOIR_MARCHE', 'VOIR_MAR'), ('ADD_FAMILLE', 'ADD_FAM'), ('ADD_COMMUNAUTE', 'ADD_COM'), ('ADD_COMMUNAUTE_ADMIN', 'ADD_COM_ADMIN'), ('ADD_FAMILLE_ADMIN', 'ADD_FAM_ADMIN'), ('ADD_ASSOCIATION_ADMIN', 'ADD_ASSO_ADMIN'), ('ADD_MARCHE', 'ADD_MAR'), ('ADD_ASSOCIATION', 'ADD_ASSO'), ('VOIR_ASSOCIATION', 'VOIR_ASSO'), ('VOIR_MEMBRE_ASSOCIATION', 'VOIR_MEM_ASSO'), ('ADD_EVENEMENT', 'ADD_EVEN'), ('ADD_LIBRAIRIE', 'ADD_LIB'), ('ADD_LIVRE', 'ADD_LIV'), ('COMMANDER_LIVRE', 'COM_LIV'), ('ADD_MEMBRE', 'ADD_MEM')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('pub_key', models.CharField(blank=True, max_length=512, null=True)),
                ('priv_key', models.CharField(blank=True, max_length=512, null=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bankno', models.CharField(blank=True, max_length=255, null=True)),
                ('membre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='arch_portal.membre')),
            ],
            options={
                'verbose_name': 'Portefeulle',
                'verbose_name_plural': 'Les portefeulles',
            },
        ),
    ]
