# Generated by Django 5.2.6 on 2026-01-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0039_alter_permission_nom_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='devise',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
