# Generated by Django 5.2.6 on 2026-01-29 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0041_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact des Utilisateurs', 'verbose_name_plural': 'Les Contacts - Utilisateurs'},
        ),
        migrations.CreateModel(
            name='PaiementLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='arch_portal.membre')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='arch_portal.livre')),
            ],
            options={
                'unique_together': {('acheteur', 'livre')},
            },
        ),
    ]
