# Generated by Django 5.2.6 on 2026-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0042_alter_contact_options_paiementlivre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementlivre',
            options={'ordering': ['-date_paiement']},
        ),
        migrations.AddField(
            model_name='paiementlivre',
            name='statut',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('EN_ATTENTE', 'En attente')], default='PAYE', max_length=20),
        ),
    ]
