# Generated by Django 5.2.6 on 2026-01-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0043_alter_paiementlivre_options_paiementlivre_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotationLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='arch_portal.membre')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='arch_portal.livre')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('livre', 'auteur')},
            },
        ),
    ]
