# Generated by Django 5.2.6 on 2026-01-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0044_notationlivre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='anciens_proprietaires',
            field=models.ManyToManyField(blank=True, related_name='livres_deja_possedes', to='arch_portal.membre'),
        ),
        migrations.AddField(
            model_name='livre',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres_possedes', to='arch_portal.membre'),
        ),
        migrations.AddField(
            model_name='paiementlivre',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiementlivre',
            name='date_remboursement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementlivre',
            name='recepteur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to='arch_portal.membre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiementlivre',
            name='reference_remboursement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiementlivre',
            name='statut',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('EN_ATTENTE', 'En attente'), ('REMBOURSE', 'Remboursé')], default='PAYE', max_length=20),
        ),
    ]
