# Generated by Django 5.2.6 on 2026-01-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0045_livre_anciens_proprietaires_livre_proprietaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlivre',
            name='recepteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to='arch_portal.membre'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='nom',
            field=models.CharField(choices=[('VOIR_FAMILLE', 'VOIR_FAM'), ('VOIR_COMMUNAUTE', 'VOIR_COM'), ('VOIR_MARCHE', 'VOIR_MAR'), ('ADD_FAMILLE', 'ADD_FAM'), ('ADD_COMMUNAUTE', 'ADD_COM'), ('ADD_COMMUNAUTE_ADMIN', 'ADD_COM_ADMIN'), ('ADD_FAMILLE_ADMIN', 'ADD_FAM_ADMIN'), ('ADD_ASSOCIATION_ADMIN', 'ADD_ASSO_ADMIN'), ('ADD_MARCHE', 'ADD_MAR'), ('ADD_ASSOCIATION', 'ADD_ASSO'), ('VOIR_ASSOCIATION', 'VOIR_ASSO'), ('VOIR_MEMBRE_ASSOCIATION', 'VOIR_MEM_ASSO'), ('ADD_EVENEMENT', 'ADD_EVEN'), ('ADD_LIBRAIRIE', 'ADD_LIB'), ('ADD_LIVRE', 'ADD_LIV'), ('COMMANDER_LIVRE', 'COM_LIV'), ('ADD_MEMBRE', 'ADD_MEM'), ('MAKE_REM', 'MAKE_REM')], max_length=255, unique=True),
        ),
    ]
