# Generated by Django 5.2.6 on 2026-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0047_categorie_livre_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librairie',
            name='livres',
        ),
        migrations.AlterField(
            model_name='livre',
            name='librairies',
            field=models.ManyToManyField(null=True, related_name='livres', to='arch_portal.librairie'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='membres_message', to='arch_portal.message'),
        ),
    ]
