# Generated by Django 5.2.6 on 2026-02-03 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0048_remove_librairie_livres_alter_livre_librairies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrairieMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('librairie', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='arch_portal.librairie')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_messages', to='arch_portal.membre')),
            ],
            options={
                'db_table': 'library_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['librairie', 'created_at'], name='library_mes_library_5cd7e1_idx')],
            },
        ),
    ]
