# Generated by Django 5.2.6 on 2026-02-03 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0049_librairiemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunauteMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communaute', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='arch_portal.communaute')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_messages', to='arch_portal.membre')),
            ],
            options={
                'db_table': 'community_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['communaute', 'created_at'], name='community_m_communi_583122_idx')],
            },
        ),
    ]
