# Generated by Django 5.2.6 on 2026-02-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_portal', '0051_alter_permission_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='generation',
            field=models.CharField(blank=True, choices=[('G1', 'Generation 1'), ('G2', 'Generation 2'), ('G3', 'Generation 3'), ('G4', 'Generation 4'), ('G5', 'Generation 5'), ('FONDATEUR', 'En attente')], max_length=50, null=1),
            preserve_default=1,
        ),
    ]
