# Generated by Django 5.0.6 on 2024-07-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('Physique', 'Librairie Physique'), ('Digitale', 'Librairie Digitale')], max_length=50, null=1)),
                ('lieu', models.CharField(max_length=250, null=True)),
                ('possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.membre')),
            ],
            options={
                'verbose_name': 'Librairie ',
                'verbose_name_plural': '  Les Librairies ',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('auteur', models.CharField(max_length=250)),
                ('domaine', models.CharField(blank=True, max_length=250, null=True)),
                ('prix', models.IntegerField(default=0)),
                ('librairies', models.ManyToManyField(null=True, related_name='mes_librairies', to='libcore.librairie')),
            ],
            options={
                'verbose_name': '  Livre de bibliotheque ',
                'verbose_name_plural': ' Les  Livres',
            },
        ),
        migrations.AddField(
            model_name='librairie',
            name='livres',
            field=models.ManyToManyField(blank=True, null=True, related_name='mes_livres', to='libcore.livre'),
        ),
    ]
