from enum import Enum


class PermissionEnum(Enum):
    VIEW_ACCOUNT = "VIEW_ACCOUNT"
    EDIT_ACCOUNT = "EDIT_ACCOUNT"
    DELETE_ACCOUNT = "DELETE_ACCOUNT"

    VIEW_COM_USERS = "VIEW_COM_USERS"
    EDIT_COM_USERS = "EDIT_COM_USERS"
    DELETE_COM_USERS = "DELETE_COM_USERS"

    VIEW_USERS = "VIEW_USERS"
    EDIT_USERS = "EDIT_USERS"
    DELETE_USERS = "DELETE_USERS"

    VIEW_SHOP = "VIEW_SHOP"
    EDIT_SHOP = "EDIT_SHOP"
    DELETE_SHOP = "DELETE_SHOP"

    VIEW_FAM = "VIEW_FAM"
    EDIT_FAM = "EDIT_FAM"
    DELETE_FAM = "DELETE_FAM"

    VIEW_ALL_ORDERS = "VIEW_ALL_ORDERS"

    VIEW_OWN_ORDERS = "VIEW_OWN_ORDERS"
    EDIT_OWN_ORDERS = "EDIT_OWN_ORDERS"
    DELETE_OWN_ORDERS = "DELETE_OWN_ORDERS"

    VIEW_CART_PRODUCTS = "VIEW_CART_PRODUCTS"
    EDIT_CART_PRODUCTS = "EDIT_CART_PRODUCTS"
    DELETE_CART_PRODUCTS = "DELETE_CART_PRODUCTS"

    VIEW_SHOP_REVIEWS = "VIEW_SHOP_REVIEWS"
    MANAGE_SHOP_REVIEWS = "MANAGE_SHOP_REVIEWS"

    VIEW_REVIEWS = "VIEW_REVIEWS"
    EDIT_REVIEWS = "EDIT_REVIEWS"
    DELETE_REVIEWS = "DELETE_REVIEWS"

    VIEW_CUSTOMER_REVIEWS = "VIEW_CUSTOMER_REVIEWS"
    MANAGE_CUSTOMERS_REVIEWS = "MANAGE_CUSTOMERS_REVIEWS"

    GENERATE_COLLECTION_LISTS = "GENERATE_COLLECTION_LISTS"
    VIEW_COLLECTION_LISTS = "VIEW_COLLECTION_LISTS"
    EDIT_COLLECTION_LISTS = "EDIT_COLLECTION_LISTS"
    DELETE_COLLECTION_LISTS = "DELETE_COLLECTION_LISTS"

    VIEW_WAREHOUSE_USERS = "VIEW_WAREHOUSE_USERS"
    EDIT_WAREHOUSE_USERS = "EDIT_WAREHOUSE_USERS"
    DELETE_WAREHOUSE_USERS = "DELETE_WAREHOUSE_USERS"

    VIEW_WAREHOUSE_STATISTICS = "VIEW_WAREHOUSE_STATISTICS"
    VIEW_SHOP_AND_MARKETPLACE_REPORTS = "VIEW_SHOP_MARKETPLACE_REPORTS"

    GENERATE_DELIVERY_LISTS = "GENERATE_DELIVERY_LISTS"
    VIEW_DELIVERY_LISTS = "VIEW_DELIVERY_LISTS"
    EDIT_DELIVERY_LISTS = "EDIT_DELIVERY_LISTS"
    DELETE_DELIVERY_LISTS = "DELETE_DELIVERY_LISTS"

    VIEW_ALL_USERS = "VIEW_ALL_USERS"
    EDIT_ALL_USERS = "EDIT_ALL_USERS"

    # VIEW_ADMIN_USERS = "VIEW_ADMIN_USERS"
    # EDIT_ADMIN_USERS = "EDIT_ADMIN_USERS"
    # DELETE_ADMIN_USERS = "DELETE_ADMIN_USERS"

    @classmethod
    def choices(cls):
        return tuple((i.value, i.name) for i in cls)
