from enum import Enum


class PermissionEnum(Enum):
    VOIR_FAM = "VOIR_FAMILLE"
    VOIR_COM = "VOIR_COMMUNAUTE"
    VOIR_MAR = "VOIR_MARCHE"

    ADD_FAM = "ADD_FAMILLE"
    ADD_COM = "ADD_COMMUNAUTE"
    ADD_COM_ADMIN = "ADD_COMMUNAUTE_ADMIN"
    ADD_FAM_ADMIN = "ADD_FAMILLE_ADMIN"
    ADD_ASSO_ADMIN = "ADD_ASSOCIATION_ADMIN"
    ADD_MAR = "ADD_MARCHE"
    ADD_ASSO = "ADD_ASSOCIATION"
    VOIR_ASSO = "VOIR_ASSOCIATION"
    VOIR_MEM_ASSO = "VOIR_MEMBRE_ASSOCIATION"

    ADD_EVEN = "ADD_EVENEMENT"
    ADD_LIB = "ADD_LIBRAIRIE"
    ADD_GALERIE = "ADD_GALERIE"
    ADD_CAGNOTTE  = "ADD_CAGNOTTE"
    CLOSE_CAGNOTTE = "CLOSE_CAGNOTTE"
    ADD_LIV = "ADD_LIVRE"
    COM_LIV = "COMMANDER_LIVRE"
    ADD_MEM = "ADD_MEMBRE"
    MAKE_REM = "MAKE_REM"

    SEE_DON = "SEE_DON"
    ADD_PRES = "ADD_PRESTATAIRE"
    DES_PRES = "DESACTIVE_PRESTATAIRE"
    EDIT_PRES = "EDIT_PRESTATAIRE"
    DEL_PRES = "DELETE_PRESTATAIRE"

    DES_PROJ = "DESACTIVE_PROJET"
    EDIT_PROJ = "EDIT_PROJET"
    DEL_PROJ = "DELETE_PROJET"
    ADD_PROJ = "ADD_PROJET"

    ADD_FORMATION = "ADD_FORMATION"
    ADD_ARTICLE = "ADD_ARTICLE"
    DEL_FORMATION = "DEL_FORMATION"
    DEL_ARTICLE = "DEL_ARTICLE"
    DES_ARTICLE = "DESACTIVE_ARTICLE"
    DES_FORMATION = "DESACTIVE_FORMATION"

    SEE_LIB_MESS = "VOIR_MESSAGES_LIBRAIRIES"
    SEE_COM_MESS = "VOIR_MESSAGES_COMMUNAUTES"

    @classmethod
    def choices(cls):
        return tuple((i.value, i.name) for i in cls)
